### ISSUE TITLE
Shorten `linkTitle` frontmatter for docs pages

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#11]
You may also want to shorten the `linkTitle` frontmatter variable for docs `_index.md` pages. Right now the long page titles makes the content menu very long.

**Comment by brian-armory** [comment]
Hey @amygroshek do you have any specific number/best practice on what the maximum character length of the `linkTitle` should be?

**Comment by amygroshek** [comment]
@brian-armory If you spin up the local hugo server for the repo `hugo server -w` and look at the docs, http://localhost:1313/docs/, you can get a sense of how the titles will wrap in the side menu. I can alter the width of the side menu, and make some font size changes, to accommodate long titles there, but my instinct there is to try to avoid wrapping beyond two lines. I'd be reluctant to set a had and fast rule, because the titles *will* wrap just fine and be legible, but maybe 30 chars or less?
