### ISSUE TITLE
YouTube videos

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#18]
> Implement videos area in Success Stories with a slider or grid that allows presentation of ~20 videos and links to the Spinnaker Youtube channel
> Design should accommodate video categorization or incorporate Youtube playlists

- What is preferred? A Hugo data file (YAML or TOML) solution that lists and/or categorizes videos? Or dynamically fetching videos from one or more playlists on YouTube channel?

**Comment by aimeeu** [comment]
on a related note, the YouTube shortcode doesn't seem to support user-specified height, width for embedded video.  Would you be able to modify the shortcode to take in set height/width so the video isn't so big?

https://s.armory.io/RBuq4mDx

**Comment by amygroshek** [comment]
- drawn from a list in data dir
- flag for landing page display
- flag for success stories page display

**Comment by amygroshek** [comment]
@aimeeu Your request won't pertain to any carousel solution since that will have to have a set height and width for all assets, and will not be entered via markdown. The YouTube template is also an internal Hugo template that cannot be accessed and modified from a Hugo site, only used. I've instead added a simple shortcode to be used instead of the internal template. It is documented in the readme.

```
{{< customyoutube id="b7BmMY1kR10" width="320px" height="240px" >}}
```
