### ISSUE TITLE
Success Stories content

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#20]
> Convert raw HTML of Success Stories page so it can be updated using markdown and yaml

Where will this be placed on the new site?

**Comment by amygroshek** [comment]
Layout for this page is coming. At present, create layout and work on list functionality for different aspects of the content.

**Comment by dnilasor** [comment]
Hey @amygroshek we'd like to rename this to a "User Stories" page. It should be called User Stories in the top nav and it will also be linked to from different things on the home page. We need a usable Hugo-ified .md version of this page since it's currently HTML/CSS not Markdown. Something organized with a config file would be great as I believe we discussed.
