### ISSUE TITLE
Docsy theme maintenance

### ISSUE THREAD

**Issue by brian-armory** [spinnaker/spinnaker.io#51]
Hi @amygroshek,

We've been working on some of our tasks for the new site and had a question about how the layout/customizations/etc are being overridden in the theme.

We didn't see overrides in the top level of `spinnaker.io`. Our understanding is that this was the most maintainable path for overrides to the Docsy theme. Can you give us some explanation as to why you're doing it this other way (modifying the theme directly)? Since no one works on Spinnaker.io full time, we are doing our best to make sure that the setup is as standard as possible so anyone can pitch in down the line.

CC @aimeeu @dorbin @dnilasor

**Comment by amygroshek** [comment]
@brian-armory I don't as a rule of thumb override a Hugo theme within the site itself for the kind of large-scale modifications of functionality you are wanting. The scss processing runs through the theme, all of the partials and shortcodes reside in the theme. Even if I can easily override, working from two different locations gets to be tricky in that it can be hard to tell what is where and what is or isn't overriding what.

**Comment by aimeeu** [comment]
Hi @amygroshek - thanks for the detailed reply!  I take full responsibility for not expressing my concerns about upgrades up front. I really do apologize profusely and appreciate all the work you've done on this project!

To answer your question about SCSS, modifying the Docsy L&F is https://www.docsy.dev/docs/adding-content/lookandfeel/ , including guidance on overriding SCSS in <project-root>/assets/scss.  Two comprehensive projects to look at for theme customization examples are:

1. Kubernetes https://kubernetes.io/ and https://github.com/kubernetes/website
2. JenkinsX  https://jenkins-x.io/ and https://github.com/jenkins-x/jx-docs

Both of those projects overrode SCSS  in <project-root>/assets/scss and page elements in <project-root>/layouts.

Unfortunately, it's really hard to convince companies to allocate tech writers to open source docs projects, so writers leave after a short period, taking knowledge with them. It's also not easy to find TWs who are also web developers, so that can make upgrading the theme, applying security patches, and upgrading Hugo a challenge. That's why we like to stay away from modifying the theme directly.  Before Kubernetes switched to using the Docsy theme, I saw some pretty sticky technical issues happen when we tried to upgrade Hugo, which didn't play nicely with the custom theme. That kind of situation is what I'm hoping to avoid in the Spinnaker website project. With my rusty web development skills, putting the customized theme elements in the project directory rather than the theme directory makes it easier for *me* to find and know what's been changed, and troubleshoot if technical issues arise. It also makes it easy for me or other project maintainers to update the theme with a `git pull` rather than doing a pull to a separate directory and then a diff of the theme. 

I can only imagine how frustrating this has been. I'd be happy to discuss via video conference or a lunch in the Madison area (are restaurants open along the Beltline??)

We'd very much like you to continue working with us!

**Comment by amygroshek** [comment]
@aimeeu @brian-armory 

I have reviewed the documentation Aimee cites. That documentation explains how to modify *variables* made available by existing theme features. It does not explain how to modify the theme scss itself where variables do not address the needed customizations. In fact, if I look at the site partials, I can see that all the the theme scss is loaded from the theme `scss/main.scss`. Because of the way the scss is compiled, if I am going to add custom scss, I will need use one of two strategies: either I will need to copy *all* of the theme scss from the theme, basically overriding all of it. Or I will have to modify the site head to load additional scss and write stronger selectors in that scss to override existing theme settings.

Given that you have strong preferences regarding theme customization, I am hoping that you will advise me as to which practice is preferable. Neither guarantees that updating the theme as a git submodule will be problem-free.

**Comment by brian-armory** [comment]
Hi @amygroshek, thanks for sharing your insight and being patient. This is a learning experience for me.

From the sounds of it, the choices boil down to

- If we want to keep some semblance of standardization between the default Docsy theme (namely the variables), option 1 is the better choice
- What are the benefits of option 2?

**Comment by amygroshek** [comment]
@brian-armory So far as I can see, the one benefit of option 2 would be that if changes are not extensive it would be more targeted, and it would be easier to track what SCSS had been modified or overridden. But given how widely the variables are used, and the extend of our changes, it may create a lot of additional work/require a **lot** of additional scss.

**Comment by dnilasor** [comment]
Hey @amygroshek and @brian-armory. Glad we're making a conscious choice here, with the knowledge that it's not perfect and that the customizations we're hoping for do add some level of maintenance complexity to the site. Based on your explanation, option 1 seems like the best course of action. Please proceed with that.

Another note, we have discussed our orientation to these architectural details as a SIG, along with our goal deadline for going live on the site (I'm the biggest obstacle to that because of our designer woes, I know)! As part of that, while we appreciate being kept in the loop on the decisions you make, we ultimately trust you to make these types of decisions with your best judgement. All we ask is that you prioritize the ability for someone who knows Hugo development to come in and make updates in the future. As long as you are doing that you can't go wrong, I don't think  : )

**Comment by amygroshek** [comment]
@dnilasor @brian-armory @aimeeu I've just merged a set of changes into `master` that moves theme overrides to site root. The theme is now a git submodule. Changes are all documented in the readme. Closing this. Feel free to reopen if necessary.
